Update submodule
badgerloop-software/chase-car-dashboard pull request #43
Opened 2023-04-10 04:21 UTC by jrvollmer

2023-04-10 04:26 UTC, EUdds requested changes
I hit the big red buttom

2023-04-10 04:26 UTC, EUdds commented on Backend/package.json
> -  "version": "1.1.2",
Do we have versioning guidelines? Like what defines a major or minor or minor minor change?

2023-04-12 05:22 UTC, jrvollmer commented on Backend/package.json
> -  "version": "1.1.2",
Soon to come, but for the sake of not blocking front end development, this needs to be merged first.

2023-04-13 01:31 UTC, EUdds approved these changes

2023-04-13 04:30 UTC, merged